# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com

# The lines below are called `modelines`. See `:help modeline`
# Feel free to remove those if you don't want/need to use them.
# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 2

before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
    # you may remove this if you don't need go generate
    - go generate ./...

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
universal_binaries:
  - replace: true
release:
  prerelease: auto
archives:
  - format: tar.gz
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
      - goos: windows
        format: zip
checksum:
  name_template: "{{ .ProjectName }}-checksums.txt"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

chocolateys:
  - name: snippetkit
    title: "Snippetkit"
    authors: Rishan Reddy
    project_url: https://github.com/rishanreddy/snippetkit
    url_template: "https://github.com/rishanreddy/snippetkit/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
    license_url: https://github.com/rishanreddy/snippetkit/blob/main/LICENSE
    project_source_url: https://github.com/rishanreddy/snippetkit
    docs_url: https://snippetkit.vercel.app/docs
    bug_tracker_url: https://github.com/rishanreddy/snippetkit/issues
    release_notes: "https://github.com/rishanreddy/snippetkit/releases/tag/v{{ .Version }}"
    api_key: "{{ .Env.CHOCOLATEY_API_KEY }}"
    source_repo: "https://push.chocolatey.org/"
    tags: "go snippetkit cli snippets"
    skip_publish: false
    description: |
      {{ .ProjectName }} installer package.
      Install snippets into your code base.

brews:
  - name: snippetkit
    commit_author:
      name: rishanreddy
    commit_msg_template: "Brew formula update for {{ .ProjectName }} version {{ .Tag }}"
    directory: Formula
    description: "Install snippets into your code base."
    license: "Apache-2.0"
    install: |
      bin.install "snippetkit"
    test: |
      system "#{bin}/snippetkit --version"
    # Repository to push the generated files to.
    repository:
      owner: rishanreddy
      name: snippetkit
      branch: main
      token: "{{ .Env.GITHUB_TOKEN }}"
