# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Snippetkit < Formula
  desc "Install snippets into your code base."
  homepage ""
  version "0.1.1"
  license "Apache-2.0"

  on_macos do
    url "https://github.com/rishanreddy/snippetkit/releases/download/v0.1.1/snippetkit_Darwin_all.tar.gz"
    sha256 "097660c243aa69ce23a987fae08e5a023fa1b15603b2cc72a7153dbffa9bce06"

    def install
      bin.install "snippetkit"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/rishanreddy/snippetkit/releases/download/v0.1.1/snippetkit_Linux_x86_64.tar.gz"
        sha256 "b3a962f6b63d9d3817cf9e5ef30f7e4b7a59f01d8010b093e02a0521f65e3c5d"

        def install
          bin.install "snippetkit"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/rishanreddy/snippetkit/releases/download/v0.1.1/snippetkit_Linux_arm64.tar.gz"
        sha256 "ed90eedd4581f4b9244033336b1a7e95b405e5af59332da4b6c2cbe70a998500"

        def install
          bin.install "snippetkit"
        end
      end
    end
  end

  test do
    system "#{bin}/snippetkit --version"
  end
end
